config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#welcome"
  
  resources :users 
  resources :trips do
    resources :activities, except: :index
    resources :posts, except: :index do 
      resources :comments, except: [:index, :show]
    end
  end
  
  get '/', to: 'sessions#welcome'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'
  get '/auth/github/callback', to: 'sessions#create'
  post '/join_trip', to: 'trips#join_trip'
  post '/leave_trip', to: 'trips#leave_trip'
end

app/models/trip.rb
class Trip < ApplicationRecord
  
  scope :past_trips, -> {where('end_date < ?', Time.now)}
  scope :future_trips, -> {where('end_date > ?', Time.now)}

  has_many :user_trips
  has_many :users, through: :user_trips
  has_many :activities, dependent: :destroy
  has_many :posts, dependent: :destroy
  belongs_to :owner, class_name: "User", foreign_key: "owner_id"
  
  accepts_nested_attributes_for :activities, reject_if: :activity_atts_blank?
  accepts_nested_attributes_for :posts, reject_if: :post_atts_blank?
  
  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :valid_date_range?
  
  def owner=(user)
    self.owner_id = user.id
    user.trips << self
  end 

  def start
    self.start_date.strftime("%b. %d, %Y")
  end
  
  def end
    self.end_date.strftime("%b. %d, %Y")
  end 
  
  def total_cost
    cost = 0
    self.activities.each do |activity|
      cost += activity.cost unless activity.cost.nil?
    end
    cost
  end 
  
  def print_total_cost
   "$" + "%.2f" % self.total_cost
  end
  
  def activity_atts_blank?(att)
    att.values.all?("")
  end
  
  def post_atts_blank?(att)
    att["title"].blank? && att["content"].blank?
  end 
  
  def valid_date_range?
    if start_date && end_date
      if start_date >  end_date
        errors.add(:end_date, "must be after start date")
      end
    end 
  end
  
  def joiner_count
    self.users.count
  end

  def includes_user?(user)
    self.users.include?(user)
  end

  def add_to_trip(user)
    user.trips << self
  end

  def remove_from_trip(user)
    user.trips.delete(self)
  end 

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  
  before_action :validate_trip_owner, only: [:edit, :update, :destroy]
  before_action :validate_user_join_or_create, only: [:join_trip, :leave_trip]

  def index
    @trips = Trip.future_trips
  end
  
  def new
    @trip = Trip.new
    @trip.activities.build
    @trip.posts.build
  end
  
  def create
    trip = Trip.new(trip_params)
    if trip.valid?
      trip.owner = current_user
      trip.save
      redirect_to trip_path(trip)
    else
      flash[:messages] = trip.errors.full_messages #rendering errors this way because i want to redirect to new action that builds on the activities and posts and will render the nested forms.
      redirect_to new_trip_path
    end
  end
  
  def show
    @trip = Trip.find(params[:id])
  end
  
  def edit
    @trip = Trip.find(params[:id]) 
  end
  
  def update
    trip = Trip.find(params[:id])
    trip.update(trip_params)
    redirect_to trip_path(trip)
  end
  
  def destroy
    trip = Trip.find(params[:id])
    trip.destroy
    redirect_to root_path
  end
  
  def join_trip
    trip = Trip.find(params[:trip_id])
    trip.add_to_trip(@user)
    redirect_to trip_path(trip)
  end
  
  def leave_trip
    trip = Trip.find(params[:trip_id])
    trip.remove_from_trip(@user)
    redirect_to trip_path(trip)
  end
  
  
  private
  
  def trip_params
    params.require(:trip).permit(:name, :start_date, :end_date, :owner_id, activities_attributes: [:name, :location, :description, :cost, :date], posts_attributes: [:title,:content,:user_id])
  end
  
  def validate_trip_owner
    trip = Trip.find(params[:id])
    redirect_to user_path(current_user) if current_user != trip.owner
  end
  
  def validate_user_join_or_create
    @user = User.find(params[:user_id]) 
    redirect_to user_path(current_user) if current_user != @user
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/edit.html.erb
<div class="d-flex p-2 justify-content-center">
<%= form_for @trip do |f| %>
<h1 class="text-center mb-4 display-3">Update Trip Details</h1>
  <div class="mb-3">
  <%=f.label :name, class: 'form-label'%>
  <%=f.text_field :name, class: 'form-control', placeholder:"Start by giving your trip a name!"%>
  </div>
  <div class="row text-center">
  <div class="col-sm input-group">
  <span class="input-group-text", id="basic-addon1">Start Date</span>
  <%=f.date_field :start_date, class: 'form-control' %>
  </div>
  <div class="col-sm input-group">
  <span class="input-group-text", id="basic-addon1">End Date</span>
  <%=f.date_field :end_date, class: 'form-control'%>
  </div>
  </div>
  <br>
  
  <div class='text-center'>
  <%=f.submit class:"btn btn-secondary"%>
  </div>
<%end%>
</div>

app/views/trips/index.html.erb
<div>
<h1 class="text-center mb-4 display-2">Upcoming Trips</h1>
  <div class="list-group">
    <% @trips.each do |trip| %>
    <a href=<%= trip_path(trip) %> class="list-group-item list-group-item-action">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"> <%= trip.name %> </h5>
        <small class="text-muted"> <%= trip.start%> - <%= trip.end %></small>
      </div>
      <p class="mb-1"><%= trip.joiner_count%> <%= 'person'.pluralize(trip.joiner_count) %> attending this trip</p>
      <small class="text-muted">Total Cost of Activities: <%= trip.print_total_cost %></small>
    </a>
  </div>
  <%end%>
</div>

app/views/trips/new.html.erb
<div class="d-flex p-2 justify-content-center">
<%= form_for @trip do |f| %>
<h1 class="text-center mb-4 display-3">Create New Trip</h1>
  <%if flash[:messages] %>
  <% flash[:messages].each do |error| %>
  <div class="alert alert-danger">
    <%= error %>
  </div>
  <%end%>
<% end %>
  <div class="mb-3">
  <%=f.label :name, class: 'form-label'%>
  <%=f.text_field :name, class: 'form-control', placeholder:"Start by giving your trip a name!"%>
  </div>
  <div class="row text-center">
  <div class="col-sm input-group">
  <span class="input-group-text", id="basic-addon1">Start Date</span>
  <%=f.date_field :start_date, class: 'form-control' %>
  </div>
  <div class="col-sm input-group">
  <span class="input-group-text", id="basic-addon1">End Date</span>
  <%=f.date_field :end_date, class: 'form-control'%>
  </div>
  <%= f.hidden_field :owner_id, value: current_user.id %>
  </div>
  <br>
  <!-- Subform for Activity Goes here-->
  <div class="d-flex justify-content-around">
  <div class="">
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#activityModalLabel">
  Add an Activity to Your Trip
</button>
<div class="modal fade" id="activityModalLabel" tabindex="-1" aria-labelledby="activityModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="activityModalLabel">Add an Activity to Your Trip</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= f.fields_for :activities do |act|%>
    <div class='mb-3'>
    <%= act.label :name, class: 'form-label' %>
    <%= act.text_field :name, class: 'form-control', placeholder:"Whatcha gonna be doing?" %>
    </div>
    <div class="mb-3">
      <%=act.label :location, class: 'form-label'%>
      <%=act.text_field :location, class: 'form-control', placeholder: "Where you going?"%>
    </div>
    <div class="mb-3">
    <%= act.label :description, class: 'form-label' %>
    <%= act.text_area :description, class: 'form-control', placeholder: "Any details people need to know?" %>
    </div>
    <div class="row">
        <div class="input-group mb-3 col-sm">
          <span class="input-group-text", id="basic-addon1">$</span>
          <%= act.text_field :cost, class: 'form-control', onkeypress: "return isNumberKey(event,this);", placeholder:"Cost per person", "aria-label":"Username", "aria-describedby":"basic-addon1"%>
        </div>
        <div class="input-group mb-3 col-sm">
          <span class="input-group-text", id="basic-addon1">Date</span>
          <%= act.date_field :date, class: 'form-control' %>
        </div>
      </div>
  <%end%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Save</button>
      </div>
    </div>
  </div>
</div>
</div>
  
  <div class="">

  <!-- Subform for Post Goes here-->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#postModalLabel">
  Add a Post to Your Trip
</button>
<div class="modal fade" id="postModalLabel" tabindex="-1" aria-labelledby="postModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="postModalLabel">Add a Post to Your Trip</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
    <%= f.fields_for :posts do |act|%>
    <div class="mb-3">
      <%= act.label :title, class: 'form-label' %>
      <%= act.text_field :title, class: 'form-control', placeholder:"Need to start a discussion for anything?" %>
    </div>
    <div class="mb-3">
      <%= act.label :content, class: 'form-label' %>
      <%= act.text_area :content, class: 'form-control', placeholder:"Go ahead ... I'm listening" %>
    </div>
    <%= act.hidden_field :user_id, value: current_user.id %>
  <%end%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Save</button>
      </div>
    </div>
  </div>
</div>
</div>
</div>
  <br>
  <div class='text-center'>
  <%=f.submit class:"btn btn-secondary"%>
  </div>
<%end%>
</div>

app/views/trips/show.html.erb
<div class="position-relative">
<div class="position-absolute top-0 end-0 text-center">
<% if @trip.owner == current_user %>
 <%= button_to "Edit Trip", edit_trip_path(@trip), method: :get, class: 'btn btn-secondary mb-3' %>
 <%= button_to "Delete Trip", trip_path(@trip), method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure that you want to delete this trip?"}%>
 <%elsif !@trip.includes_user?(current_user)%>
 <%= button_to "Join Trip", join_trip_path, method: :post, class: 'btn btn-secondary mb-3', params: {trip_id:@trip.id, user_id:current_user} %>
 <%elsif @trip.includes_user?(current_user)%>
 <%= button_to "Leave Trip", leave_trip_path, method: :post, class: 'btn btn-secondary mb-3', params: {trip_id:@trip.id, user_id:current_user} %>
<%end%>
</div>
</div>
<h1 class="display-3 mb-4 text-center"><%=@trip.name%></h1>
<h4 class="display-7 mb-4 text-center"><%=@trip.start%> - <%=@trip.end%> </h4>
<div class="mb-4">
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>
<div class="mb-4">
<h1 class="display-6 mb-4">People Coming on this Trip</h1>
<ul class="list-group list-group-horizontal">
<% @trip.users.each do |user| %>
  <li class="list-group-item ustify-content-between align-items-center">
  <% if @trip.owner == user %><span class="badge bg-primary rounded-pill">Owner</span><%end%>
  <%= user.username %>
  </li>
  <%end%>
</ul>
</div>
<h1 class="display-6 mb-4">Activities</h1>
<div class="accordion mb-3" id="accordionPanelsStayOpenExample">
<% @trip.activities.each do |activity| %>
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-heading<%=activity.id.to_s%>">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseAct<%=activity.id.to_s%>" aria-expanded="false" aria-controls="panelsStayOpen-collapseAct<%=activity.id.to_s%>">
        <%= activity.act_date%> - <%= activity.name%>
      </button>
    </h2>
    <div id="panelsStayOpen-collapseAct<%=activity.id.to_s%>" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingAct<%=activity.id.to_s%>">
      <div class="accordion-body">
        <div class="mb-3">
          <%= activity.description%>
        </div>
        <div>
          <%= link_to "View Activity Details", trip_activity_path(@trip,activity), class: "text-muted" %>
        </div>
      </div>
    </div>
  </div>
<%end%>
</div>
<% if @trip.includes_user?(current_user)%>
<div class="mb-3 text-center">
<a class="btn btn-outline-primary" href=<%= new_trip_activity_path(@trip)%> role="button">Add an Activity</a>
</div>
<%end%>
<h1 class="display-6 mb-4">Posts</h1>
<div class="accordion mb-3" id="accordionPanelsStayOpenExample">
<% @trip.posts.each do |post| %>
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingPost<%=post.id.to_s%>">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapsePost<%=post.id.to_s%>" aria-expanded="false" aria-controls="panelsStayOpen-collapsePost<%=post.id.to_s%>">
        <%= post.title%>
      </button>
    </h2>
    <div id="panelsStayOpen-collapsePost<%=post.id.to_s%>" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingPost<%=post.id.to_s%>">
      <div class="accordion-body">
        <div class="mb-3">
        <div class="user d-flex flex-row align-items-center"> <span><small class="font-weight-bold text-primary"><%= post.user.username%> </small> </div>
          <%= post.content%>
        </div>
        <div>
          <%= link_to "View Post Discussion", trip_post_path(@trip,post), class: "text-muted" %>
        </div>
      </div>
    </div>
  </div>
<%end%>
</div>
<%if @trip.includes_user?(current_user)%>
<div class="mb-3 text-center">
<a class="btn btn-outline-primary" href=<%= new_trip_post_path(@trip)%> role="button">Add a Post</a>
</div>
<%end%>