config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#welcome"
  
  resources :users 
  resources :trips do
    resources :activities, except: :index
    resources :posts, except: :index do 
      resources :comments, except: [:index, :show]
    end
  end
  
  get '/', to: 'sessions#welcome'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'
  get '/auth/github/callback', to: 'sessions#create'
  post '/join_trip', to: 'trips#join_trip'
  post '/leave_trip', to: 'trips#leave_trip'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  has_many :user_trips
  has_many :trips, through: :user_trips
  has_many :user_activities
  has_many :activities, through: :user_activities
  has_many :comments
  has_many :posts
  
  validates :username, presence: true
  validates :username, uniqueness: true
  
  def owned_trips
    Trip.all.select {|trip| trip.owner == self}
  end
  
  def non_owned_trips
    Trip.all.select {|trip| trip.users.include?(self) && trip.owner != self}
  end
  
  def delete_user
    self.owned_trips.each {|trip| trip.destroy}
    self.non_owned_trips.each {|trip| trip.remove_from_trip(self)}
    self.posts.each {|post| post.destroy}
    self.comments.each {|cmt| cmt.destroy}
    self.destroy
  end 
  
  def self.create_from_oauth(omniauth_details)
    user = User.find_or_create_by(uid: omniauth_details['uid'])
    user.username = omniauth_details['info']['nickname'] 
    user.password_digest = SecureRandom.urlsafe_base64
    user.save
    user
  end 

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :require_login, only: [:new,:create]
  before_action :validate_current_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    if logged_in?
      redirect_to user_path(current_user)
    else
      @user = User.new
    end
  end
  
  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end    
  end
  
  
  def edit
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to user_path(current_user)
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
  
  def destroy
    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user)
    else
      session.clear
      user.delete_user
      redirect_to root_path
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username,:password)
  end
  
  def form_fields_completed?
    !params[:user][:username].nil? && !params[:user][:password].nil?
  end
  
  def validate_current_user
    user = User.find(params[:id])
    redirect_to user_path(current_user) if current_user != user
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_userform.html.erb
<div class="d-flex p-2 justify-content-center">
<%= form_for @user do |f| %>
<%if @user.errors %>
    <% @user.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger"><%= msg %></div>
      <%end%>
  <% end %>
  <div class='mb-3'>
  <%= f.label :username, class: 'form-label' %>
  <%= f.text_field :username, class: 'form-control' %>
  </div>
  <div class='mb-3'>
  <%= f.label :password , class: 'form-label'%>
  <%= f.password_field :password, class: 'form-control'%>
  </div>
  <div class="text-center">
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<%end%>
</div>

app/views/users/edit.html.erb
<h1 class="text-center display-3 mb-4">Edit Profile</h1>
<%= render partial: 'userform'%>

app/views/users/index.html.erb
<h1>All Users</h1>
<ul>
<% @users.each do |user| %>
<li><%= link_to user.username, user_path(user) %></li>
<%end%>
</ul>

app/views/users/new.html.erb
<h1 class="text-center display-3 mb-4">Sign Up</h1>
<%= render partial: 'userform'%>

app/views/users/show.html.erb
<% if @user == current_user %>
<div class="position-relative">
<div class="position-absolute top-0 end-0 text-center">
 <%= button_to "Edit Profile", edit_user_path(@user), method: :get, class: 'btn btn-secondary mb-3' %>
 <%= button_to "Delete Profile", user_path(@user), method: :delete, class: 'btn btn-danger mb-3', data: {confirm: "Are you sure that you want to delete your profile"}%>
</div>
</div>
<%end%>
<h1 class="display-3 mb-4 text-center"><%=@user.username%></h1>
<h1 class="mb-4 display-6">Trips Owned</h1>
 <%= button_to "Create Trip", new_trip_path, method: :get, class: 'btn btn-outline-primary mb-3' %>
  <div class="list-group">
    <% @user.owned_trips.each do |trip| %>
    <a href=<%= trip_path(trip) %> class="list-group-item list-group-item-action">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"> <%= trip.name %> </h5>
        <small class="text-muted"> <%= trip.start%> - <%= trip.end %></small>
      </div>
      <p class="mb-1"><%= trip.joiner_count%> <%= 'person'.pluralize(trip.joiner_count) %> attending this trip</p>
      <small class="text-muted">Total Cost of Activities: $<%= trip.total_cost %></small>
    </a>
  </div>
  <%end%>
</div>
<h1 class="mb-4 display-6 mt-3">Trips Joined</h1>
  <div class="list-group">
    <% @user.non_owned_trips.each do |trip| %>
    <a href=<%= trip_path(trip) %> class="list-group-item list-group-item-action">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"> <%= trip.name %> </h5>
        <small class="text-muted"> <%= trip.start%> - <%= trip.end %></small>
      </div>
      <p class="mb-1"><%= trip.joiner_count%> <%= 'person'.pluralize(trip.joiner_count) %> attending this trip</p>
      <small class="text-muted">Total Cost of Activities: <%= trip.print_total_cost %></small>
    </a>
  </div>
  <%end%>
</div>
</div>