config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#welcome"
  
  resources :users 
  resources :trips do
    resources :activities, except: :index
    resources :posts, except: :index do 
      resources :comments, except: [:index, :show]
    end
  end
  
  get '/', to: 'sessions#welcome'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'
  get '/auth/github/callback', to: 'sessions#create'
  post '/join_trip', to: 'trips#join_trip'
  post '/leave_trip', to: 'trips#leave_trip'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :trip
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :validate_post_owner, only: [:edit,:update] #only post owners should be able to modify their posts
  before_action :validate_post_owner_and_trip_owner, only: [:destroy] #trip owners should be able to delete posts
  before_action :validate_part_of_trip, only: [:new, :create]

  def new
    @trip = Trip.find(params[:trip_id])
    @post = Post.new
  end

  def create
    @trip = Trip.find(params[:trip_id])
    @post = @trip.posts.build(post_params)
    if @post.valid?
      @post.save
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  def show
    @trip = Trip.find(params[:trip_id])
    @post = Post.find(params[:id])
  end

  def edit
    @trip = Trip.find(params[:trip_id])
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @trip = @post.trip
    if @post.update(post_params)
      redirect_to trip_post_path(@post.trip,@post)
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    trip = post.trip
    post.destroy
    redirect_to trip_path(trip)
  end

  private
  
  def post_params
    params.require(:post).permit(:title, :content, :user_id)
  end

  def validate_post_owner
    post = Post.find(params[:id])
    redirect_to user_path(current_user) if current_user != post.user
  end

  def validate_post_owner_and_trip_owner
    post = Post.find(params[:id])
    redirect_to user_path(current_user) if current_user != post.user && current_user != post.trip.owner
  end

  def validate_part_of_trip 
    trip = Trip.find(params[:trip_id]) 
    redirect_to trip_path(trip), notice: "Must join trip to add posts" unless trip.includes_user?(current_user)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_postform.html.erb
<%= form_for ([trip,post]) do |pst|%>
<%if post.errors %>
    <% post.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger"><%= msg %></div>
      <%end%>
  <% end %>
    <h1 class="text-center mb-4 display-6"><%= form_title%></h1>
  <%if flash[:messages] %>
  <% flash[:messages].each do |error| %>
  <div class="alert alert-danger">
    <%= error %>
  </div>
  <%end%>
<% end %>
    <div class="mb-3">
      <%= pst.label :title, class: 'form-label' %>
      <%= pst.text_field :title, class: 'form-control', placeholder:"What what you like to start a post on?" %>
    </div>
    <div class="mb-3">
      <%= pst.label :content, class: 'form-label' %>
      <%= pst.text_area :content, class: 'form-control', placeholder:"Go ahead ... I'm listening" %>
    </div>
      <%= pst.hidden_field :user_id, value: current_user.id %>
    <div class="text-center">
  <%= pst.submit class:'btn btn-primary' %>
  </div>
<%end%>

app/views/posts/edit.html.erb
<%= render partial: 'postform', locals: {post: @post, trip: @trip, form_title: "#{@post.title}"} %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<%= render partial: 'postform', locals: {post: @post, trip: @trip, form_title: "Add Post to #{@trip.name}"} %>

app/views/posts/show.html.erb
<div class="position-relative mb-3">
  <div class="top-0 start-0">
  <%= button_to 'Back', trip_path(@trip), method: :get, class: 'btn btn-outline-primary'%>
  </div>
</div>
<% if @trip.owner == current_user || @post.user == current_user%>
<div class="position-relative">
<div class="position-absolute top-0 end-0 text-center">
 <%unless @post.user != current_user%><%= button_to "Edit Post", edit_trip_post_path(@trip,@post), method: :get, class: 'btn btn-secondary mb-3' %><% end%>
 <%= button_to "Delete Post", trip_post_path(@trip,@post), method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure that you want to delete this post?"}%>
</div>
</div>
<%end%>
<h1 class="display-3 mb-4"><%=@post.title%></h1>
<p class="lead">
<%= @post.content%>
</p>
<em>Posted by <%= @post.user.username %></em>
<div class="container mt-5">
    <div class="row d-flex justify-content-left">
        <div class="">
            <div class="headings d-flex justify-content-between align-items-center mb-3">
                <h2>Comments</h2>
                <div class="mb-3 text-center">
                    <a class="btn btn-outline-primary" href=<%= new_trip_post_comment_path(@trip, @post)%> role="button">Add a Comment</a>
                </div>
            </div>
            <% @post.comments.each do |comment|%>
            <!-- Loop Start here -->
            <div class="card p-3 mt-2">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="user d-flex flex-row align-items-center"> <span><small class="font-weight-bold text-primary"><%= comment.user.username%> </small> <br>
                    <small class="font-weight-bold"><%= comment.content%></small></span> </div>
                </div>
                <%if comment.user == current_user %>
                <div class="action d-flex justify-content-between mt-2 align-items-center">
                    <div class="reply px-4"> <small><%= link_to 'Edit Comment', edit_trip_post_comment_path(@trip,@post,comment), class: 'text-muted' %></small> <span class="dots"></span> <small> | </small> <span class="dots"></span> <small><%= link_to 'Delete Comment', trip_post_comment_path(@trip,@post,comment), method: :delete, class: 'text-danger', data: {confirm: "Are you sure that you want to delete this comment?"}  %></small> </div>
                </div>
                <%elsif current_user == comment.post.trip.owner %>
                <div class="action d-flex justify-content-between mt-2 align-items-center">
                    <div class="reply px-4"> </small> <span class="dots"></span> <small><%= link_to 'Delete Comment', trip_post_comment_path(@trip,@post,comment), method: :delete, class: 'text-danger', data: {confirm: "Are you sure that you want to delete this comment?"}  %></small> </div>
                </div>
                <%end%>
            </div>
            <%end%>
            <!-- Loop End Here -->
        </div>
    </div>
</div>