config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#welcome"
  
  resources :users 
  resources :trips do
    resources :activities, except: :index
    resources :posts, except: :index do 
      resources :comments, except: [:index, :show]
    end
  end
  
  get '/', to: 'sessions#welcome'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'
  get '/auth/github/callback', to: 'sessions#create'
  post '/join_trip', to: 'trips#join_trip'
  post '/leave_trip', to: 'trips#leave_trip'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Trippin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  

  <body>
  <div class="container sticky-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand mb-0 h1" href=<%= root_path %>>Trippin</a>
      <ul class="navbar-nav">
        <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.username %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href=<%= new_trip_path%>>Create Trip</a></li>
            <li><a class="dropdown-item" href=<%= trips_path%>>View Trips</a></li>
            <li><a class="dropdown-item" href=<%= user_path(current_user)%>>View Profile</a></li>
            <li><a class="dropdown-item text-danger" href=<%= logout_path %>>Log Out</a></li>
          </ul>
        </li>
        <%end%>
      </ul>
  </div>
</nav>
</div>

    <section class="container mt-3">
    <%= yield %>
    </section>
  </body>
</html>